FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json /app/
RUN npm ci

COPY . /app

RUN npm run build -- --configuration production

FROM nginx:1.27-alpine

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

# Angular (builder moderno) genera dist/<app>/browser
COPY --from=build /app/dist/logiciel-crv-frontend/browser /usr/share/nginx/html

EXPOSE 80
